
package View;

import Model.UsuarioLogado;


public class CartaoView extends javax.swing.JFrame {

    
    public CartaoView() {
        
        initComponents();
        txtNomeUsuario.setText(UsuarioLogado.getInstance().getNome());
        txtNomeCartao.setText(UsuarioLogado.getInstance().getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntPix = new javax.swing.JButton();
        bntPaginaInicial = new javax.swing.JButton();
        txtNomeCartao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        bntPix.setText("PIX");
        bntPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPixActionPerformed(evt);
            }
        });
        jPanel1.add(bntPix);
        bntPix.setBounds(80, 207, 90, 23);

        bntPaginaInicial.setText("Página inicial");
        bntPaginaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPaginaInicialActionPerformed(evt);
            }
        });
        jPanel1.add(bntPaginaInicial);
        bntPaginaInicial.setBounds(30, 260, 140, 23);

        txtNomeCartao.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeCartao.setFont(new java.awt.Font("Yaro Op Thin", 1, 12)); // NOI18N
        txtNomeCartao.setForeground(new java.awt.Color(198, 25, 88));
        jPanel1.add(txtNomeCartao);
        txtNomeCartao.setBounds(510, 380, 160, 20);

        jLabel4.setFont(new java.awt.Font("Yaro St Thin", 1, 13)); // NOI18N
        jLabel4.setText("Limite: 1.000,00");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 87, 130, 20);

        txtNomeUsuario.setFont(new java.awt.Font("Yaro St Thin", 0, 14)); // NOI18N
        txtNomeUsuario.setText("Nome usuário");
        jPanel1.add(txtNomeUsuario);
        txtNomeUsuario.setBounds(340, 70, 420, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cartaofill.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntPaginaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPaginaInicialActionPerformed
        // TODO add your handling code here:
        
        ContaView conta = new ContaView();
        conta.setVisible(true);
        conta.pack();
        dispose();
        
    }//GEN-LAST:event_bntPaginaInicialActionPerformed

    private void bntPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPixActionPerformed
        // TODO add your handling code here:
        PixView pix = new PixView();
        pix.setVisible(true);
        pix.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_bntPixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartaoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntPaginaInicial;
    private javax.swing.JButton bntPix;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtNomeCartao;
    private javax.swing.JLabel txtNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
