
package View;

import Model.UsuarioLogado;


public class ContaView extends javax.swing.JFrame {
    
    public ContaView(){
        initComponents();
        
        String nomeCliente = UsuarioLogado.getInstance().getNome();
        // permite inserir o nome do cliente ao acessar a conta 
        txtOlaUsuario.setText("Olá, " + nomeCliente);
        
        
        setLocationRelativeTo(null); // center
        setResizable(false); // nao maximiza 
        
        
        bntPix.setContentAreaFilled(false);
        bntPix.setBorderPainted(false);
        bntPix.setOpaque(false);
        
        bntCartoes.setContentAreaFilled(false);
        bntCartoes.setBorderPainted(false);
        bntCartoes.setOpaque(false);
        
        bntVerExtrato.setContentAreaFilled(false);
        bntVerExtrato.setBorderPainted(false);
        bntVerExtrato.setOpaque(false);
    }/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntPix = new javax.swing.JToggleButton();
        bntCartoes = new javax.swing.JButton();
        txtOlaUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtSaldoConta = new javax.swing.JLabel();
        txtValor = new javax.swing.JLabel();
        bntVerExtrato = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conta - CypherBank");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        bntPix.setFont(new java.awt.Font("Yaro St Thin", 0, 14)); // NOI18N
        bntPix.setText("PIX");
        bntPix.setBorder(null);
        bntPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPixActionPerformed(evt);
            }
        });
        jPanel1.add(bntPix);
        bntPix.setBounds(480, 290, 30, 30);

        bntCartoes.setFont(new java.awt.Font("Yaro Rg Thin", 0, 14)); // NOI18N
        bntCartoes.setText("Cartões");
        bntCartoes.setBorder(null);
        bntCartoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCartoesActionPerformed(evt);
            }
        });
        jPanel1.add(bntCartoes);
        bntCartoes.setBounds(480, 390, 80, 30);

        txtOlaUsuario.setFont(new java.awt.Font("Yaro St Thin", 1, 24)); // NOI18N
        txtOlaUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtOlaUsuario.setText("Olá, nome do usuário");
        jPanel1.add(txtOlaUsuario);
        txtOlaUsuario.setBounds(160, 70, 290, 30);

        jSeparator1.setBackground(new java.awt.Color(182, 28, 76));
        jSeparator1.setForeground(new java.awt.Color(182, 28, 76));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(660, 240, 80, 3);

        txtSaldoConta.setFont(new java.awt.Font("Yaro St Thin", 1, 14)); // NOI18N
        txtSaldoConta.setText("Saldo em conta");
        jPanel1.add(txtSaldoConta);
        txtSaldoConta.setBounds(50, 230, 130, 30);

        txtValor.setFont(new java.awt.Font("Yaro St Thin", 0, 13)); // NOI18N
        txtValor.setText("R$ 1.000,00");
        jPanel1.add(txtValor);
        txtValor.setBounds(50, 250, 90, 30);

        bntVerExtrato.setFont(new java.awt.Font("Yaro St Thin", 1, 12)); // NOI18N
        bntVerExtrato.setForeground(new java.awt.Color(182, 28, 76));
        bntVerExtrato.setText("Ver extrato");
        bntVerExtrato.setBorder(null);
        bntVerExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVerExtratoActionPerformed(evt);
            }
        });
        jPanel1.add(bntVerExtrato);
        bntVerExtrato.setBounds(650, 220, 100, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yaro St Thin", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(198, 25, 88));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Frame 15.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPixActionPerformed
        // TODO add your handling code here:
        
        PixView pix = new PixView();
        pix.setVisible(true);
        pix.pack();
        pix.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_bntPixActionPerformed

    private void bntVerExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVerExtratoActionPerformed
        // TODO add your handling code here:
        //VerExtratoView extrato = new VerExtratoView();
        //extrato.setVisible(true);
       // extrato.pack();
        //extrato.setLocationRelativeTo(null);
        //this.dispose();
        String cpf = UsuarioLogado.getInstance().getCpf();
        VerExtratoView extrato = new VerExtratoView();
        extrato.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_bntVerExtratoActionPerformed

    private void bntCartoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCartoesActionPerformed
        // TODO add your handling code here:
        
        CartaoView cartao = new CartaoView();
        cartao.setVisible(true);
        cartao.pack();
        cartao.setLocationRelativeTo(null);
        this.dispose();
        
       
    }//GEN-LAST:event_bntCartoesActionPerformed
     
               
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCartoes;
    private javax.swing.JToggleButton bntPix;
    private javax.swing.JToggleButton bntVerExtrato;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txtOlaUsuario;
    private javax.swing.JLabel txtSaldoConta;
    private javax.swing.JLabel txtValor;
    // End of variables declaration//GEN-END:variables
}
