
package View;

import Controller.DepositoController;
import Controller.PixController;
import DAO.ContaBD;
import DAO.PixBD;
import Model.UsuarioLogado;
import javax.swing.JOptionPane;


public class PixView extends javax.swing.JFrame {
    
    
    
    public PixView() {
        initComponents();
        
        txtnomeUsuario.setText(UsuarioLogado.getInstance().getNome());
        // centralizat
        setLocationRelativeTo(null);
        // não maximizar a interface 
        setResizable(false);
        
        getRootPane().setDefaultButton(bntEnviar);
        getRootPane().setDefaultButton(bntEnviarDeposito);
        // deixar o botão cadastrar funcional em conjunto ao enter do pc
        //getRootPane().setDefaultButton(bntLogin);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        Chave1 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        bntEnviarDeposito = new javax.swing.JButton();
        Valor1 = new javax.swing.JLabel();
        txtValorDeposito = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Chave = new javax.swing.JLabel();
        txtChave = new javax.swing.JTextField();
        bntEnviar = new javax.swing.JButton();
        Valor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        bntCartoes = new javax.swing.JButton();
        bntPaginaInicial = new javax.swing.JButton();
        txtnomeUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CypherBank - PIX");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(198, 25, 88));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Chave1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Chave1.setText("CPF");

        bntEnviarDeposito.setBackground(new java.awt.Color(198, 25, 88));
        bntEnviarDeposito.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bntEnviarDeposito.setForeground(new java.awt.Color(255, 255, 255));
        bntEnviarDeposito.setText("Enviar");
        bntEnviarDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEnviarDepositoActionPerformed(evt);
            }
        });

        Valor1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Valor1.setText("Valor");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntEnviarDeposito)
                    .addComponent(txtValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Chave1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Valor1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Chave1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Valor1)
                .addGap(5, 5, 5)
                .addComponent(txtValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(bntEnviarDeposito)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Depositar", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Chave.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Chave.setText("Chave");

        bntEnviar.setBackground(new java.awt.Color(198, 25, 88));
        bntEnviar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bntEnviar.setForeground(new java.awt.Color(255, 255, 255));
        bntEnviar.setText("Enviar");
        bntEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEnviarActionPerformed(evt);
            }
        });

        Valor.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Valor.setText("Valor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntEnviar)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChave, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Chave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Chave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Valor)
                .addGap(5, 5, 5)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(bntEnviar)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transferir", jPanel2);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(210, 210, 590, 290);

        bntCartoes.setText("Cartões");
        bntCartoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCartoesActionPerformed(evt);
            }
        });
        jPanel1.add(bntCartoes);
        bntCartoes.setBounds(80, 207, 80, 23);

        bntPaginaInicial.setText("Página inicial");
        bntPaginaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPaginaInicialActionPerformed(evt);
            }
        });
        jPanel1.add(bntPaginaInicial);
        bntPaginaInicial.setBounds(30, 260, 140, 23);

        txtnomeUsuario.setFont(new java.awt.Font("Yaro St Thin", 0, 14)); // NOI18N
        txtnomeUsuario.setText("Nome usuário");
        jPanel1.add(txtnomeUsuario);
        txtnomeUsuario.setBounds(340, 70, 390, 20);

        jLabel4.setFont(new java.awt.Font("Yaro St Thin", 1, 13)); // NOI18N
        jLabel4.setText("Saldo: R$1.000,00");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 87, 280, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pix.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 850, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntPaginaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPaginaInicialActionPerformed
        // TODO add your handling code here:
        ContaView conta = new ContaView();
        conta.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_bntPaginaInicialActionPerformed

    private void bntCartoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCartoesActionPerformed
        // TODO add your handling code here:
        
        CartaoView cartao = new CartaoView();
        cartao.setVisible(true);
        cartao.pack();
        cartao.setLocationRelativeTo(null);
        this.dispose();
        
        
    }//GEN-LAST:event_bntCartoesActionPerformed

    private void bntEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEnviarActionPerformed
        // TODO add your handling code here:

        String chave = txtChave.getText();
        double valor = Double.parseDouble(txtValor.getText());

        System.out.println( "Dados: "  + " " + chave + " " + valor);

        PixController novoPix = new PixController();
        novoPix.salvarPix(chave, valor);

        txtChave.setText("");
        txtValor.setText("");
      

    }//GEN-LAST:event_bntEnviarActionPerformed

    private void bntEnviarDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEnviarDepositoActionPerformed
        // TODO add your handling code here:
        
        String cpf = txtCPF.getText();
        double valor = Double.parseDouble(txtValorDeposito.getText());

        System.out.println( "Dados: "  + " " + cpf + " " + valor);

        DepositoController novoDeposito = new DepositoController();
        novoDeposito.salvarDeposito(cpf, valor);
        
        txtCPF.setText("");
        txtValorDeposito.setText("");
    }//GEN-LAST:event_bntEnviarDepositoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PixView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PixView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PixView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PixView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PixView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Chave;
    private javax.swing.JLabel Chave1;
    private javax.swing.JLabel Valor;
    private javax.swing.JLabel Valor1;
    private javax.swing.JButton bntCartoes;
    private javax.swing.JButton bntEnviar;
    private javax.swing.JButton bntEnviarDeposito;
    private javax.swing.JButton bntPaginaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtChave;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValorDeposito;
    private javax.swing.JLabel txtnomeUsuario;
    // End of variables declaration//GEN-END:variables
}
