
package View;

import java.util.List;
import javax.swing.table.DefaultTableModel;


public class VerExtratoView extends javax.swing.JFrame {

    
    public VerExtratoView() {
        initComponents();
          setLocationRelativeTo(null);
        // não maximizar a interface 
        setResizable(false);
        carregarExtrato();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     private void carregarExtrato() {
    DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
    modelo.setRowCount(0); // limpa a tabela
    
    Controller.ExtratoController controller = new Controller.ExtratoController();

    List<Model.PixModel> listaPix = controller.listarTransacoesPIX();
    
    
    for (Model.PixModel pix : listaPix) {
        modelo.addRow(new Object[]{
            pix.getChave(),
            pix.getValor(),
            pix.getData().toString(),
            pix.getTipo()
                
        });
    }
    
         
    
    
    List<Model.DepositoModel> listaDeposito = controller.listarTransacoesDEPOSITO();
    
    for (Model.DepositoModel deposito : listaDeposito) {
        modelo.addRow(new Object[]{
            deposito.getOrigem(),
            deposito.getValor(),
            deposito.getData(),
            deposito.getTipo(),
            deposito.getCpf()
            
                
        });
    }
    
    
}    

    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        bntPix = new javax.swing.JButton();
        bntCartoes = new javax.swing.JButton();
        bntPaginaInicial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CypherBank - Extrato");

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Destino", "Valor", "Data/Hora", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(Tabela);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(220, 12, 560, 460);

        bntPix.setText("PIX");
        bntPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPixActionPerformed(evt);
            }
        });
        jPanel1.add(bntPix);
        bntPix.setBounds(80, 207, 90, 23);

        bntCartoes.setText("Cartões");
        bntCartoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCartoesActionPerformed(evt);
            }
        });
        jPanel1.add(bntCartoes);
        bntCartoes.setBounds(80, 250, 90, 23);

        bntPaginaInicial.setText("Página inicial");
        bntPaginaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPaginaInicialActionPerformed(evt);
            }
        });
        jPanel1.add(bntPaginaInicial);
        bntPaginaInicial.setBounds(30, 290, 140, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Conta.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntCartoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCartoesActionPerformed
        // TODO add your handling code here:

        CartaoView cartao = new CartaoView();
        cartao.setVisible(true);
        cartao.pack();
        cartao.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_bntCartoesActionPerformed

    private void bntPaginaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPaginaInicialActionPerformed
        // TODO add your handling code here:
        ContaView conta = new ContaView();
        conta.setVisible(true);
        dispose();

    }//GEN-LAST:event_bntPaginaInicialActionPerformed

    private void bntPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPixActionPerformed
        // TODO add your handling code here:
        PixView pix = new PixView();
        pix.setVisible(true);
        pix.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_bntPixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerExtratoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerExtratoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerExtratoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerExtratoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerExtratoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton bntCartoes;
    private javax.swing.JButton bntPaginaInicial;
    private javax.swing.JButton bntPix;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
